=== koobai/blog/schemas/data/landmark-route-library.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Jingzhe landmark route library",
  "type": "array",
  "items": {
    "type": "object",
    "required": ["key", "name", "unit", "kind", "max_count", "distance_km", "geometry", "source"],
    "properties": {
      "key": {"type": "string", "minLength": 1},
      "name": {"type": "string", "minLength": 1},
      "unit": {"type": "string"},
      "kind": {"enum": ["distance", "elevation"]},
      "reference_km": {"type": "number", "minimum": 0},
      "reference_meters": {"type": "number", "minimum": 0},
      "min_km": {"type": "number", "minimum": 0},
      "max_km": {"type": "number", "minimum": 0},
      "max_count": {"type": "integer", "minimum": 1},
      "preferred_groups": {
        "type": "array",
        "items": {"enum": ["ride", "run", "walk", "hike"]},
        "uniqueItems": true
      },
      "path_type": {"type": "string"},
      "costing": {"type": "string"},
      "distance_km": {"type": "number", "minimum": 0},
      "geometry": {"type": "string"},
      "source": {"type": "string"}
    },
    "additionalProperties": false
  }
}

=== koobai/blog/assets/data/exercise/landmark-routes.json
[
  {
    "key": "track",
    "name": "操场",
    "unit": "圈",
    "reference_km": 0.4,
    "kind": "distance",
    "min_km": 0.2,
    "max_km": 4.8,
    "max_count": 12,
    "preferred_groups": ["run", "walk"],
    "path_type": "loop",
    "costing": "pedestrian",
    "distance_km": 0.404,
    "geometry": "ozvwD}ve|UG?G@GBGBGDGDCFCFCHCF?HCHBH?HBHBFBFBFFFFBFDF@F@F?vC?F?JAFAFEDCDGBGFGBG?IBI?I?ICI?GCIGGCGEEEEGCGCKAG?wC?",
    "source": "representative public stadium track aligned to OpenStreetMap way 1160421821"
  },
  {
    "key": "bai_causeway",
    "name": "白堤",
    "unit": "趟",
    "reference_km": 1,
    "kind": "distance",
    "min_km": 0.6,
    "max_km": 5.5,
    "max_count": 6,
    "preferred_groups": ["run", "walk", "hike"],
    "path_type": "line",
    "costing": "pedestrian",
    "distance_km": 2.259,
    "geometry": "{_twDgch|UY]SXMOKNGFCDEDEEo@q@{BsCiEmDoDsCeLeJcCyBo@k@oDwCSOA?_@U@G?SAQSgAq@eCIWW_Am@eBcCiLWk@Oq@Q{@AYF]`@i@\\OTGt@ETAx@I`Da@x@Ev@STETMDEDOBa@?u@GaFAQEwDCcBLM\\S",
    "source": "OpenStreetMap via Valhalla"
  },
  {
    "key": "qiantang_bridge",
    "name": "钱塘江大桥",
    "unit": "趟",
    "reference_km": 1.453,
    "kind": "distance",
    "min_km": 1.2,
    "max_km": 8.5,
    "max_count": 6,
    "preferred_groups": ["ride", "run", "walk"],
    "path_type": "line",
    "costing": "pedestrian",
    "distance_km": 3.737,
    "geometry": "__jwDo_g|UAF@HTj@Rn@?z@?h@EXBNAPKV@PJTTRZ\\PFJHHRLJLFHTXXZTBx@?P?PCjA?JS`@P`@yAVdAdAVH\\An@YlIeDbU}I`_@kOrCiAPOJMJQF]Ce@Qu@Ok@Cg@AmAFqBUBM@CFmARG@EEMKUAQBKPI@QM]Be@NEDCDAGSoAu@mFSFNfAT|Ab@dCF^PjANbA\\|A\\xAPfAPn@ZlAF^`@jCTrBTlANn@Tz@ZdAbAbClAtCh@hAVd@HLTb@RIbC}@|F_C",
    "source": "OpenStreetMap via Valhalla"
  },
  {
    "key": "hubin_pedestrian_street",
    "name": "湖滨步行街",
    "unit": "趟",
    "reference_km": 2,
    "kind": "distance",
    "min_km": 1.5,
    "max_km": 10.0,
    "max_count": 5,
    "preferred_groups": ["run", "walk"],
    "path_type": "line",
    "costing": "pedestrian",
    "distance_km": 2.545,
    "geometry": "c}uwDk`k|U^FT}AJBd@RLDVNNFTHz@VJBt@Lr@HB@`@B`@@`@BPDVQ`Au@nAaAHITWLMrBoAd@[`@Yv@e@RIn@Od@EJA`@Cn@??c@AkATWl@AAiA?C?GAI?SN?pGOL?P?VCB?`FGzBCfBCvFIPAjFEnBCzDOR?rAClEINARCN?nEMr@AlBEfAAl@AGcDzDQ[gEAS",
    "source": "OpenStreetMap via Valhalla"
  },
  {
    "key": "su_causeway",
    "name": "苏堤",
    "unit": "趟",
    "reference_km": 2.8,
    "kind": "distance",
    "min_km": 2.3,
    "max_km": 16.8,
    "max_count": 6,
    "preferred_groups": ["ride", "run", "walk", "hike"],
    "path_type": "line",
    "costing": "pedestrian",
    "distance_km": 4.043,
    "geometry": "cjuwD}hg|U??OZUd@YVWb@Oj@FTPx@HRd@dALb@Vx@hAf@t@d@v@r@`ArAj@VnART@\\D\\DTHRJr@R|@^x@p@Xd@RXEb@A`@Hj@Th@DVQb@QXE\\F^?Zv@x@p@d@dA`@p@Xp@^`@f@`AjALFZRTRRTJLr@t@`@Jf@Db@NF[?wAAm@PaALu@NeACcAbBc@PG|A_@l@M|JoBz@QLElD}@fFqA|HgBx@Sh@KVEtXoF~A[`ASVEzGyAhB_@PE|IcCn@Q~@]xHyDp@a@fBgA`Bs@hD_Bp@UDUHEDORKPI",
    "source": "OpenStreetMap via Valhalla"
  },
  {
    "key": "yang_causeway",
    "name": "杨公堤",
    "unit": "趟",
    "reference_km": 3.4,
    "kind": "distance",
    "min_km": 2.8,
    "max_km": 20.4,
    "max_count": 6,
    "preferred_groups": ["ride", "run", "walk", "hike"],
    "path_type": "line",
    "costing": "bicycle",
    "distance_km": 4.54,
    "geometry": "giuwDczd|Un@_@XEjBcAPWNEGeEp@R\\Jh@Jj@B`IWj@@f@JbF`BtBZ\\GnEeBjBBjDC|FKN?RAp@AfBMn@Gr@EPArHg@LAbEWrAS|Cs@DAhCq@~@SVGfDw@|@Ul@QzB]`@DTFRFNFD@^T~D|EdFhGnAl@zAR|AQd@Op@WvBsAh@o@DEFGt@}@fHqLZi@lAoBrBkDpAcBrBuA|FwDj@lEAj@Op@A`AZhCP|ALt@Zd@BFjCrCRDHg@L]Vc@`@[HGr@e@z@o@|@o@rBuALINj@]NLl@",
    "source": "OpenStreetMap via Valhalla"
  },
  {
    "key": "wentao_riverside",
    "name": "闻涛沿江线",
    "unit": "趟",
    "reference_km": 4.4,
    "kind": "distance",
    "min_km": 3.5,
    "max_km": 26.4,
    "max_count": 6,
    "preferred_groups": ["ride", "run", "walk"],
    "path_type": "line",
    "costing": "bicycle",
    "distance_km": 6.416,
    "geometry": "ewmwDysl|Us@JBUAw@CMGMwAyAiBkBs@u@SQMOKMU_@ISEQEWK}AI_AOmBeFj@QBI@[MIEIKOQCO?YJ]H]HUnLgA`BG^AvBMf@C`@A`@?b@@l@FbHr@tAPb@_@NOTWHGL?FAdC{A`@O^O\\QrBy@`Dy@jACz@c@jMsHtLwG`V{MxJoF\\S~NcIlAQn@U~@i@hAo@nBkAjCuADJLX~@|BrBlFn@`BBDL\\JZVj@l@dBVt@`BlEvD~JFVVKnCkAzFaCxAk@|CwAJCTK`@MVKJCrA]dDo@z@Q~@QrCm@vA]b@KlI_BpFWnEIx@fUHbK",
    "source": "OpenStreetMap via Valhalla"
  },
  {
    "key": "jiuxi_baita",
    "name": "九溪白塔线",
    "unit": "趟",
    "reference_km": 7,
    "kind": "distance",
    "min_km": 5.2,
    "max_km": 35.0,
    "max_count": 5,
    "preferred_groups": ["run", "walk", "hike"],
    "path_type": "line",
    "costing": "pedestrian",
    "distance_km": 3.956,
    "geometry": "muhwDw_b|UnAMTAPGNMNMVKVOLKPWLSPMl@UPKNO\\i@NWRU^Yh@a@PSV_@NQJETGfAQfAQdAMl@AN@JDPRJNHFHAL?rDW|@Sl@UNUB[?_@?QFQh@m@j@}@Ve@CG?G?I@IDGFEFCF?H@JI^Yg@gAGOEGg@sAQm@y@eCgAoCi@wA_@{@s@qA{@sA{AwAaB{BsAkBgAsB_DeGm@{@qDaDWWyGqJoKkW[?]RSAQMsAkBYa@gBiCk@iAOi@_AqCQq@Mc@KSSMS?}A@Y?i@GBkA?Q?QCy@CmAAUAUa@kICOC]S{BK_AMy@Ss@Ow@Gi@?y@Hy@?w@Qq@Sq@",
    "source": "OpenStreetMap via Valhalla"
  },
  {
    "key": "imperial_city_route",
    "name": "皇城根线",
    "unit": "趟",
    "reference_km": 8,
    "kind": "distance",
    "min_km": 6.0,
    "max_km": 40.0,
    "max_count": 5,
    "preferred_groups": ["run", "walk", "hike"],
    "path_type": "loop",
    "costing": "pedestrian",
    "distance_km": 7.18,
    "geometry": "igqwDctm|Uh@LObAEZKx@SdBSlBGd@APCTGb@TBFX`@~ABR|Ff@bFb@bL~@tDZF?pDSbBHxCJ`@BD?LNdAL`APzA\\VHXHr@Rp@R\\LNBR@P?RCTEVIVM^SJVL\\?N~Az@RHFD_AbCM\\tA|@Df@VCFAAICo@Ce@AQ@U\\?^Fx@d@h@Rd@FXBN@X?HAb@Gh@GXCJAFADATEZED?HjBD`AB^BVFTJTLLVRPTLXB\\NITELA^j@TLLDTAPEJANALHDHFPJVHl@FZHNHL@HHNE\\KPETI`@?L?MHa@DUJQD]IOAIIMIOG[Im@KWGQEIMIO@K@QDU@MEUM_@k@M@UDOHC]MYQUWSMMKUGUCWC_@EaAIkBE?[DUDE@G@K@YBi@Fc@FI@Y?OAYCe@Gi@Sy@e@_@G]?D[@QDWPwAR_BZqBFYDc@CYLs@fCcDBCfCcD?EI_@CQCc@Cy@AOAS?GK_CE_@Ei@CUVQz@[f@ORKb@WHKv@s@PQH@H@DBNHHBJA??Ra@LK@ME[SY_@UOK[a@S]Wg@Ma@Mk@Ks@Ca@AiAFq@LeAR_Ao@SaB}@y@]eD_BgBcAEs@Gl@Gj@E^cARw@KMCLBv@JXD`@DKl@e@fEGj@{Ck@cEu@{E{@wAWgEw@QEeCg@{@Wo@Yu@e@eBaAoIuEKVo@rA{BhCw@lBYx@Yz@w@jCiBfGw@|Co@zB[nAeA~BOv@ENCNi@M",
    "source": "OpenStreetMap via Valhalla"
  },
  {
    "key": "jiangnan_avenue",
    "name": "江南大道",
    "unit": "趟",
    "reference_km": 9,
    "kind": "distance",
    "min_km": 6.7,
    "max_km": 45.0,
    "max_count": 5,
    "preferred_groups": ["ride", "run", "walk"],
    "path_type": "line",
    "costing": "bicycle",
    "distance_km": 10.152,
    "geometry": "a{gwDo_j|U{BLmANBoCBwAGoAUwF@OBe@hACrBIpAEt@CjAEzAGtAEZALAIq@{@sGCSK_A_A{He@qCg@aCUkASiAi@kCG[I]Om@CM_AgCgAuDkAuDOa@w@kCqB}G}@qCIWmA{Da@sAWy@]cAeAgD_@sAGSiBsF_@kAUy@m@uB]_Aa@iA]mAnCkAzFaCxAk@|CwAJCTK`@MVKM[MYk@aBk@sBYy@[s@Uq@GSSi@oFaRc@cAs@oAO]EWIOEMCGYcAIQEIKa@eAyCWeAKw@Ci@E[U_AsBsE[o@sAaEoAiDuAeEMa@SYuCqH[u@Qs@u@cBMK_A_CwA_D}@yBc@eA}@uByBkFSa@a@m@_BcEWe@wBaFU}@GGUe@o@gBSc@g@cAuEyKiCuGOYSa@k@iAkGcNQ_@u@{AuDkIO]cA}BeDsHEGKSQ][o@IS_DkHaFiKc@_AeJiS[SKWDo@oCsGKSs@}AIs@_@w@_BiD_AsBaC_GYeAUkAKk@CEEIICm@JM?IK_AuBEUIW@o@Ja@PUz@c@PGj@LNIfDcC~EuCt@[NGVKtAg@fASt@OvASJARCHq@Ag@Am@@UAM?mCCaL@MByED_A",
    "source": "OpenStreetMap via Valhalla"
  },
  {
    "key": "west_lake",
    "name": "西湖",
    "unit": "圈",
    "reference_km": 10,
    "kind": "distance",
    "min_km": 7.5,
    "max_km": 60.0,
    "max_count": 6,
    "preferred_groups": ["ride", "run", "walk", "hike"],
    "path_type": "loop",
    "costing": "bicycle",
    "distance_km": 13.847,
    "geometry": "_iuwDazg|UHPJEH@x@o@TQn@q@HIw@sAQo@e@_BSw@@Eb@Ya@eB_A}A{AeCQUCKEKC[@s@BmAEUi@{AEMSwAEc@CUMuA?U?o@Nm@BEv@iA@G?SAQSgAq@eCIWW_Am@eBcCiLWk@Kw@Ok@C_@DSFMPIVGx@UnB]pCg@hAElAO@?XSVc@AwACiFAGMiHEyEEqDr@Iz@EfCIN?~FK^AlGE\\A?KJ[?GA_@EmCCgBEkBCkEdF|@p@NhAX`AVr@PpFAJpF@rD?D?RAJItBEb@G`@IPAL?NLLPF@BZ^P`@h@fAbAlBl@f@LJ|BfBXTHDh@HPB|AD|AKVA`CQxAGJ?T?N?v@PVP`Ar@h@ZVJtDrAVHx@XhAf@lAp@d@Vx@f@n@`@l@^bA|@d@`@VHRDjFi@jAEVAnCMh@C~DQ~Br@|BhAFHzAjBd@n@jAr@NFPFdARd@H|B`@z@v@VVXVNHpAj@PDvAVvBUfCWt@AfBEfAIjB^xAf@pAb@d@RfBr@pElBZ_B[~AGXADG`@E\\ADCFQFo@Eo@E_@CSFSBYAa@A_@BQ@UHYJUT[NWHa@HEDEHALAHIDK@Q?YEWA[C@RD^JxA?t@?PE`@E\\i@|BCdA@~@PnBLlAB^Ft@LxA`@|DRlBDjA@b@@v@HbATnAXt@JZHRj@zALXfApC~@hChAzCTp@\\jA^jADNbCvHyDfCYPcC|AyE|CsChBWNeC`B{BvAoBvAc@l@o@z@uBhDuAvBiIpMWXa@h@g@j@sBnAqAn@uARmASwA}@Eh@D|@E}@Di@sGcIyBoCa@u@][c@@YBe@TyBf@m@NKBsFrAUDGB_@HmBb@_@H_ATC?EBwAVqATmDVqBLoHd@uCRw@BuGLkD?kBAIE{AcBPe@Jq@EmA?y@@[@MDg@@KDWD]BMBMDOF[?wAAm@PaALu@NeACcAu@iGAIEUs@wEGWeBkC{I{Is@mAe@s@QOm@_@KAOKOSOe@Q_AOy@CK[gA_@gA[{@KWa@iAS[g@]IGQK]SSQa@g@_AeACCIHo@p@UPy@n@IAKDIQ",
    "source": "OpenStreetMap via Valhalla"
  },
  {
    "key": "jingshan_trail",
    "name": "径山古道",
    "unit": "趟",
    "reference_km": 10,
    "kind": "distance",
    "min_km": 7.5,
    "max_km": 60.0,
    "max_count": 6,
    "preferred_groups": ["run", "walk", "hike"],
    "path_type": "line",
    "costing": "pedestrian",
    "distance_km": 12.573,
    "geometry": "o`lxDslqzUtH~CwApGQGY?ODSPOZCd@FXLTHHq@j@{@`AoDlEmE~DyDtCmEvDmG~EsHbFkC~AgBjAYRiAhAg@x@u@fCg@zB{@zDUbAmD`Ee@\\{E~EyE`FkFnFiCpCqCpF{BvFcAdEIR_AxAQTC?KTaCvDoFrGuDfFyBzC}H~JaB~AoD`CuAdAi@`@MJqAxAWXaA~@c@`@{AvAQZQb@In@Df@@bAa@xAu@pBiAjCoBhC}A`B]\\YZo@n@[ZYl@s@rAiBtF[`BRn@j@lBn@hEAfAcBbFa@~AV|HCbQHrF@n@J~FSrF?jA@xAApAYd@MRsCxCa@r@{@~AYf@S`@iChFiArDW`BEXGXC`@I~@Zd@d@t@d@f@^XjCh@tCb@zBl@jBl@h@^j@f@dClC`@b@NPnCvCjAzALN|@jAdCdDlClDTXLP|AnBdBlBTNZRp@d@k@j@Np@Ht@Lv@Rp@Nv@Rv@Xv@GZD?L@ZTPNPZJTZd@@TDf@\\rEnAzBX^d@p@fA|AfAtAlBtAr@f@`@f@Vp@nAtGN|@VpAlAfEL`@Ct@Jd@DZGj@Ql@Sh@Cb@DJDJHHL@^En@IP?P?RPHVLTRJPNBJ@PId@Qf@?JBLJJLBT?JDHJB`@DRHNZLNFFLNt@D^H\\FLHFHFPFv@At@Gb@Hf@ZTDt@MLAPDRLJLJHJ@T?NEL@l@R`@PFJDLAT_@~@c@dAK^CT@ZDJNBNGv@YZAVQX_@\\Wh@K\\b@\\^|Ab@hDn@fC`BpCzB`ArBrAlCP\\HNZFRAd@W`@?~AHfAd@v@QXQx@^h@j@b@h@^d@`@^b@HXHNBHL@FF@BC@G@MDEF@JJF`@H\\JXD\\BNB^?FABEAEIIIG@?JBJ@b@N^LNBNGJCLAHBHHDVD`@HTFFR@l@@TBVBNHT@ZAX@VAPERENIDC?CEASACC?CDEHEACG@SEQGMG@AFAHADELEHAFARBh@AV",
    "source": "OpenStreetMap via Valhalla"
  },
  {
    "key": "chaoshan_loop",
    "name": "超山环线",
    "unit": "圈",
    "reference_km": 10.7,
    "kind": "distance",
    "min_km": 8.0,
    "max_km": 64.2,
    "max_count": 6,
