=== koobai/blog/schemas/data/movie.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Jingzhe movie data",
  "type": "array",
  "items": {
    "type": "object",
    "required": ["id", "title", "rating", "create_time"],
    "properties": {
      "id": {"type": ["string", "number"]},
      "type": {"type": "string"},
      "title": {"type": "string", "minLength": 1},
      "year": {"type": ["string", "number"]},
      "rating": {"type": "number", "minimum": 0, "maximum": 5},
      "comment": {"type": "string"},
      "link": {"type": "string"},
      "create_time": {"type": "string", "minLength": 1},
      "color_scheme": {
        "type": "object",
        "properties": {
          "primary_color_light": {"type": "string"},
          "primary_color_dark": {"type": "string"},
          "secondary_color": {"type": "string"},
          "is_dark": {"type": "boolean"}
        },
        "additionalProperties": true
      }
    },
    "additionalProperties": true
  }
}

=== koobai/blog/assets/movie.json
[
  {
    "id": "36246195",
    "type": "movie",
    "title": "蜘蛛侠：崭新之日",
    "year": "2026",
    "rating": 5,
    "comment": "人类万恶之源～",
    "link": "https://movie.douban.com/subject/36246195/",
    "create_time": "2026-07-29 21:39:17",
    "color_scheme": {
      "_base_color": [
        0.9444444444444444,
        0.16666666666666666,
        0.1411764705882353
      ],
      "_avg_color": [
        0.01851851851851845,
        0.1578947368421052,
        0.6705882352941176
      ],
      "primary_color_light": "a58a93",
      "primary_color_dark": "7f6a71",
      "secondary_color": "f9f4f6",
      "is_dark": true
    }
  },
  {
    "id": "35875462",
    "type": "movie",
    "title": "群星闪耀时",
    "year": "2026",
    "rating": 5,
    "comment": "英雄是千千万万的平凡人，这才是群星闪耀时～",
    "link": "https://movie.douban.com/subject/35875462/",
    "create_time": "2026-07-25 23:23:10",
    "color_scheme": {
      "_base_color": [
        0.03472222222222223,
        0.5,
        0.18823529411764706
      ],
      "_avg_color": [
        0.07142857142857141,
        0.48514851485148514,
        0.396078431372549
      ],
      "primary_color_light": "724539",
      "primary_color_dark": "4c2e26",
      "secondary_color": "f9f5f4",
      "is_dark": true
    }
  },
  {
    "id": "36882191",
    "type": "movie",
    "title": "八仙！",
    "year": "2026",
    "rating": 5,
    "comment": "有意思，喜欢。八仙原来是因为天庭为了颜面才封的，讽刺太讽刺了～",
    "link": "https://movie.douban.com/subject/36882191/",
    "create_time": "2026-07-14 21:50:06",
    "color_scheme": {
      "_base_color": [
        0.03479853479853481,
        0.674074074074074,
        0.5294117647058824
      ],
      "_avg_color": [
        0.04819277108433736,
        0.6014492753623188,
        0.5411764705882353
      ],
      "primary_color_light": "a54d36",
      "primary_color_dark": "7f3b29",
      "secondary_color": "f9f5f4",
      "is_dark": true
    }
  },
  {
    "id": "36877245",
    "type": "movie",
    "title": "火遮眼",
    "year": "2026",
    "rating": 5,
    "comment": "哐哐哐打就对了，爽。另外看不得这种闺女受欺负的情节",
    "link": "https://movie.douban.com/subject/36877245/",
    "create_time": "2026-06-13 23:28:14",
    "color_scheme": {
      "_base_color": [
        0.0,
        0.009852216748768438,
        0.796078431372549
      ],
      "_avg_color": [
        0.0,
        0.04761904761904746,
        0.5764705882352941
      ],
      "primary_color_light": "a5a4a4",
      "primary_color_dark": "7f7e7e",
      "secondary_color": "f9f4f4",
      "is_dark": true
    }
  },
  {
    "id": "35010610",
    "type": "movie",
    "title": "挽救计划",
    "year": "2026",
    "rating": 5,
    "comment": "之前有关外星人的题材，不是我打你就是你欺负我。这个相互依赖相互信任，没有黑森林法则，蛮好。",
    "link": "https://movie.douban.com/subject/35010610/",
    "create_time": "2026-05-11 10:58:46",
    "color_scheme": {
      "_base_color": [
        0.09444444444444446,
        0.46875,
        0.25098039215686274
      ],
      "_avg_color": [
        0.07627118644067797,
        0.48360655737704916,
        0.47843137254901963
      ],
      "primary_color_light": "725b3c",
      "primary_color_dark": "4c3c28",
      "secondary_color": "f9f7f4",
      "is_dark": true
    }
  },
  {
    "id": "36749573",
    "type": "movie",
    "title": "极限审判",
    "year": "2026",
    "rating": 3,
    "comment": "前面还不错，紧张刺激～AI 终究会统治人类。可能有生之年还能见识到～",
    "link": "https://movie.douban.com/subject/36749573/",
    "create_time": "2026-04-19 12:04:06",
    "color_scheme": {
      "is_dark": true,
      "primary_color_light": "204372",
      "_base_color": [
        0.595959595959596,
        0.717391304347826,
        0.1803921568627451
      ],
      "secondary_color": "f4f7f9",
      "_avg_color": [
        0.5798611111111112,
        0.4485981308411215,
        0.4196078431372549
      ],
      "primary_color_dark": "152c4c"
    }
  },
  {
    "id": "26404869",
    "type": "movie",
    "title": "惊天魔盗团3",
    "year": "2025",
    "rating": 2,
    "comment": "啥啥啥，无聊老套，第一部太惊艳了",
    "link": "https://movie.douban.com/subject/26404869/",
    "create_time": "2026-04-10 08:39:24",
    "color_scheme": {
      "is_dark": true,
      "primary_color_light": "4570a5",
      "_base_color": [
        0.5928571428571429,
        0.5785123966942148,
        0.4745098039215686
      ],
      "secondary_color": "f4f7f9",
      "_avg_color": [
        0.5863095238095237,
        0.4148148148148148,
        0.5294117647058824
      ],
      "primary_color_dark": "35567f"
    }
  },
  {
    "id": "35341071",
    "type": "tv",
    "title": "七王国的骑士 第一季",
    "year": "2026",
    "rating": 3,
    "comment": "简短而无聊。一开场冰与火的主题曲出来激动了下，紧接着就是喷屎，靠～",
    "link": "https://movie.douban.com/subject/35341071/",
    "create_time": "2026-03-23 09:05:06",
    "color_scheme": {
      "is_dark": true,
      "primary_color_light": "6f7251",
      "_base_color": [
        0.1851851851851852,
        0.2903225806451613,
        0.12156862745098039
      ],
      "secondary_color": "f9f9f4",
      "_avg_color": [
        0.2051282051282052,
        0.13131313131313127,
        0.38823529411764707
      ],
      "primary_color_dark": "4a4c36"
    }
  },
  {
    "id": "36318037",
    "type": "tv",
    "title": "唐朝诡事录之长安",
    "year": "2025",
    "rating": 4,
    "comment": "标记下，不是说有多好看，而是在目前一众类似题材中，还是蛮喜欢这个系列的～",
    "link": "https://movie.douban.com/subject/36318037/",
    "create_time": "2026-03-16 10:55:46",
    "color_scheme": {
      "is_dark": true,
      "primary_color_light": "a56652",
      "_base_color": [
        0.03846153846153846,
        0.5,
        0.10196078431372549
      ],
      "secondary_color": "f9f6f4",
      "_avg_color": [
        0.07228915662650602,
        0.6148148148148148,
        0.5294117647058824
      ],
      "primary_color_dark": "7f4e3f"
    }
  },
  {
    "id": "36176155",
    "type": "movie",
    "title": "一战再战",
    "year": "2025",
    "rating": 3,
    "comment": "标记下，为什么都说非常好看，可能自己太肤浅，觉得又长又无聊~",
    "link": "https://movie.douban.com/subject/36176155/",
    "create_time": "2026-03-16 09:12:02",
    "color_scheme": {
      "is_dark": true,
      "primary_color_light": "a59b93",
      "_base_color": [
        0.07051282051282047,
        0.11206896551724135,
        0.9098039215686274
      ],
      "secondary_color": "f9f7f4",
      "_avg_color": [
        0.05434782608695652,
        0.2486486486486487,
        0.7254901960784313
      ],
      "primary_color_dark": "7f7771"
    }
  },
  {
    "id": "35689244",
    "type": "movie",
    "title": "F1：狂飙飞车",
    "year": "2025",
    "rating": 5,
    "comment": "标记下，当时在电影院看很大的感受就是，第一人称视角与背景音乐的那种很闷跌荡起伏声，太震撼～",
    "link": "https://movie.douban.com/subject/35689244/",
    "create_time": "2026-03-14 18:27:03",
    "color_scheme": {
      "is_dark": true,
      "primary_color_light": "72443b",
      "_base_color": [
        0.029411764705882342,
        0.48571428571428577,
        0.13725490196078433
      ],
      "secondary_color": "f9f5f4",
      "_avg_color": [
        0.06451612903225806,
        0.29807692307692313,
        0.40784313725490196
      ],
      "primary_color_dark": "4c2d27"
    }
  },
  {
    "id": "36317421",
    "type": "tv",
    "title": "太平年",
    "year": "2026",
    "rating": 4,
    "comment": "看看当今的世界，太平多重要～俞灏明越来越喜欢～",
    "link": "https://movie.douban.com/subject/36317421/",
    "create_time": "2026-03-14 17:38:15",
    "color_scheme": {
      "is_dark": true,
      "primary_color_light": "72696e",
      "_base_color": [
        0.9166666666666666,
        0.07692307692307693,
        0.20392156862745098
      ],
      "secondary_color": "f9f4f7",
      "_avg_color": [
        0.04999999999999993,
        0.21978021978021978,
        0.3568627450980392
      ],
      "primary_color_dark": "4c4649"
    }
  },
  {
    "id": "35424715",
    "type": "tv",
    "title": "生命树",
    "year": "2026",
    "rating": 4,
    "comment": "小队没散的时候很好看，多杰是一个对得起国家但对不起家庭的一个人～",
    "link": "https://movie.douban.com/subject/35424715/",
    "create_time": "2026-03-14 17:36:07",
    "color_scheme": {
      "is_dark": true,
      "primary_color_light": "707269",
      "_base_color": [
        0.2037037037037038,
        0.07894736842105272,
        0.4470588235294118
      ],
      "secondary_color": "f8f9f4",
      "_avg_color": [
        0.18333333333333326,
        0.0826446280991735,
        0.4745098039215686
      ],
      "primary_color_dark": "4b4c46"
    }
  },
  {
    "id": "36474027",
    "type": "movie",
    "title": "镖人：风起大漠",
    "year": "2026",
    "rating": 5,
    "comment": "爽，精彩，喜欢～吴师傅跟谢主厨打得很燃。能看到李连杰、张晋、吴京同时打斗更是感动～",
    "link": "https://movie.douban.com/subject/36474027/",
    "create_time": "2026-02-21 21:43:02",
    "color_scheme": {
      "is_dark": true,
      "primary_color_light": "a56035",
      "_base_color": [
        0.06349206349206349,
        0.6774193548387096,
        0.48627450980392156
      ],
      "secondary_color": "f9f6f4",
      "_avg_color": [
        0.07317073170731707,
        0.5503355704697986,
        0.5843137254901961
      ],
      "primary_color_dark": "7f4a29"
    }
  },
  {
    "id": "37311135",
    "type": "movie",
    "title": "飞驰人生3",
    "year": "2026",
    "rating": 4,
    "comment": "可能是系列太雷同了？这部笑点没上部高，不过拿冠军总是让人心潮澎湃！",
    "link": "https://movie.douban.com/subject/37311135/",
    "create_time": "2026-02-21 15:47:00",
    "color_scheme": {
      "is_dark": true,
      "primary_color_light": "6a4572",
      "_base_color": [
        0.8030303030303031,
        0.39285714285714285,
        0.10980392156862745
      ],
      "secondary_color": "f8f4f9",
      "_avg_color": [
        0.9166666666666666,
        0.375,
        0.18823529411764706
      ],
      "primary_color_dark": "472e4c"
    }
  },
  {
    "id": "37149448",
    "type": "tv",
    "title": "塔尔萨之王 第三季",
    "year": "2025",
    "rating": 4,
    "comment": "就默默的看史泰龙装逼～蛮好。",
    "link": "https://movie.douban.com/subject/37149448/",
    "create_time": "2026-01-29 17:18:23",
    "color_scheme": {
